# type: ignore
# pylint: disable
"""Plot BERTScore F1 against mutation iterations.

This script reads the CSV produced by `plots/bertscore_iter.py` and
shows box plots per iteration window to summarize the distribution of
metric values and reduce noise.
"""

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from scipy import stats


def detect_metrics(df: pd.DataFrame) -> dict[str, dict[str, str | None]]:
    """Detect metric columns (mean/std) from the aggregated CSV."""
    metrics: dict[str, dict[str, str | None]] = {}
    for col in df.columns:
        if not col.endswith("_mean"):
            continue
        base = col.removesuffix("_mean")
        std_col = f"{base}_std" if f"{base}_std" in df.columns else None
        metrics[base] = {
            "mean": col,
            "std": std_col,
            "count": "count" if "count" in df.columns else None,
        }
    return metrics


def add_window_labels(df: pd.DataFrame, window_size: int) -> pd.DataFrame:
    """Annotate rows with window boundaries/labels based on iteration."""
    if window_size <= 0:
        raise ValueError("window_size must be positive")

    work = df.copy()
    work["window_start"] = ((work["iteration"] - 1) // window_size) * window_size + 1
    work["window_end"] = work["window_start"] + window_size - 1
    work["window_label"] = work.apply(
        lambda row: f"{int(row.window_start)}-{int(row.window_end)}", axis=1
    )
    work["window_center"] = work["window_start"] + (window_size - 1) / 2
    return work


def plot_metric(
    df: pd.DataFrame,
    metric: str,
    mean_col: str,
    window_size: int,
    output_path: Path,
) -> Path:
    """Plot a single metric and return the saved path."""
    work = add_window_labels(
        df[["iteration", mean_col]].rename(columns={mean_col: "metric"}), window_size
    )
    order = (
        work[["window_label", "window_start"]]
        .drop_duplicates()
        .sort_values("window_start")["window_label"]
        .tolist()
    )
    mean_line = (
        work.groupby("window_label")["metric"].mean().reindex(order).reset_index()
    )

    regression = None
    if work["iteration"].nunique() >= 2:
        fit = stats.linregress(df["iteration"], df[mean_col])
        centers = (
            work[["window_label", "window_center"]]
            .drop_duplicates()
            .set_index("window_label")
            .reindex(order)["window_center"]
        )
        reg_y = fit.intercept + fit.slope * centers
        regression = {
            "x": list(range(len(order))),
            "y": reg_y,
            "label": f"Linear fit (β={fit.slope:.2e}, p={fit.pvalue:.3f}, R²={fit.rvalue**2:.3f})",
        }

    fig, ax = plt.subplots(figsize=(10, 4))
    sns.boxplot(
        data=work,
        x="window_label",
        y="metric",
        order=order,
        ax=ax,
        color="lightgray",
    )
    ax.plot(
        range(len(order)), mean_line["metric"], marker="o", color="C0", label="Mean"
    )
    if regression:
        ax.plot(
            regression["x"],
            regression["y"],
            color="goldenrod",
            linestyle="--",
            label=regression["label"],
        )
    ax.set_xlabel("Mutation iterations")
    ax.set_ylabel("BERTScore F1")
    ax.grid(True, linestyle="--", alpha=0.3)
    ax.set_xticks(range(len(order)))
    ax.set_xticklabels(order, rotation=30, ha="right")
    ax.legend()
    fig.tight_layout()

    output_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_path, dpi=500, bbox_inches="tight")
    plt.close(fig)
    return output_path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Create plots of BERTScore F1 versus mutation iteration. "
            "Input should be the CSV generated by plots/bertscore_iter.py."
        )
    )
    parser.add_argument("input_csv", help="Aggregated metrics CSV path.")
    parser.add_argument(
        "--metrics",
        nargs="*",
        default=None,
        help="Specific metrics to plot (base names without _mean); defaults to all detected.",
    )
    parser.add_argument(
        "-o",
        "--output",
        dest="output",
        default=None,
        help=(
            "Output path. If multiple metrics are plotted, the metric name is inserted "
            "before the file extension. Defaults to plots/figures/<metric>.png"
        ),
    )
    parser.add_argument(
        "-w",
        "--window-size",
        type=int,
        default=20,
        help="Window size (in iterations) for smoothing (default: 20).",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    df = pd.read_csv(args.input_csv)
    if df.empty:
        raise SystemExit("Aggregated metrics CSV is empty; nothing to plot.")

    metrics = detect_metrics(df)
    if not metrics:
        raise SystemExit("No metric columns found (expected *_mean).")

    selected = metrics
    if args.metrics:
        selected = {m: metrics[m] for m in args.metrics if m in metrics}
        missing = [m for m in args.metrics if m not in metrics]
        if missing:
            print(f"Skipping unknown metrics: {', '.join(missing)}")
        if not selected:
            raise SystemExit("None of the requested metrics were found in the CSV.")

    saved_paths: list[Path] = []
    base_output = Path(args.output) if args.output else None
    default_dir = Path("plots/figures")
    for metric, cols in selected.items():
        if base_output:
            if len(selected) == 1:
                output_path = base_output
            else:
                output_path = base_output.with_stem(f"{base_output.stem}_{metric}")
        else:
            output_path = default_dir / f"{metric}.png"
        saved_paths.append(
            plot_metric(
                df,
                metric=metric,
                mean_col=cols["mean"],  # type: ignore
                window_size=args.window_size,
                output_path=output_path,
            )
        )

    print("Saved plots:")
    for path in saved_paths:
        print(f"- {path}")


if __name__ == "__main__":
    main()
