"""Plot semantic integrity metrics against mutation iterations.

This script reads the CSV produced by `plots/iteration_metrics.py` and
generates simple line charts to visualize how semantic metrics change
as the number of mutation iterations increases.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Mapping

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns


def detect_metrics(df: pd.DataFrame) -> dict[str, str]:
    """Detect metric mean columns from the aggregated CSV."""
    metrics: dict[str, str] = {}
    for col in df.columns:
        if not col.endswith("_mean"):
            continue
        base = col.removesuffix("_mean")
        metrics[base] = col
    return metrics


def plot_metric(
    df: pd.DataFrame,
    metric: str,
    mean_col: str,
    output_dir: Path,
) -> Path:
    """Plot a single metric and return the saved path."""
    x = df["iteration"]
    y = df[mean_col]

    fig, ax = plt.subplots(figsize=(6, 4))
    sns.lineplot(x=x, y=y, marker="o", ax=ax, label=metric)
    ax.set_title(f"{metric.replace('_', ' ').title()} vs. Iteration")
    ax.set_xlabel("Mutation iteration")
    ax.set_ylabel(metric.replace("_", " ").title())
    ax.grid(True, linestyle="--", alpha=0.3)
    ax.set_xticks(sorted(df["iteration"].unique()))
    fig.tight_layout()

    output_dir.mkdir(parents=True, exist_ok=True)
    out_path = output_dir / f"{metric}.png"
    fig.savefig(out_path, dpi=300, bbox_inches="tight")
    plt.close(fig)
    return out_path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Create plots of semantic metrics versus mutation iteration. "
            "Input should be the CSV generated by plots/iteration_metrics.py."
        )
    )
    parser.add_argument("input_csv", help="Aggregated metrics CSV path.")
    parser.add_argument(
        "--metrics",
        nargs="*",
        default=None,
        help="Specific metrics to plot (base names without _mean); defaults to all detected.",
    )
    parser.add_argument(
        "--output-dir",
        default="plots/figures",
        help="Directory to save plots.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    df = pd.read_csv(args.input_csv)
    if df.empty:
        raise SystemExit("Aggregated metrics CSV is empty; nothing to plot.")

    metrics = detect_metrics(df)
    if not metrics:
        raise SystemExit("No metric columns found (expected *_mean).")

    selected = metrics
    if args.metrics:
        selected = {m: metrics[m] for m in args.metrics if m in metrics}
        missing = [m for m in args.metrics if m not in metrics]
        if missing:
            print(f"Skipping unknown metrics: {', '.join(missing)}")
        if not selected:
            raise SystemExit("None of the requested metrics were found in the CSV.")

    output_dir = Path(args.output_dir)
    saved_paths: list[Path] = []
    for metric, cols in selected.items():
        saved_paths.append(
            plot_metric(
                df,
                metric=metric,
                mean_col=cols,
                output_dir=output_dir,
            )
        )

    print("Saved plots:")
    for path in saved_paths:
        print(f"- {path}")


if __name__ == "__main__":
    main()
