"""Plot semantic integrity metrics against mutation iterations.

This script reads the CSV produced by `plots/iteration_metrics.py` and
shows box plots per iteration window to summarize the distribution of
metric values and reduce noise.
"""

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns


def detect_metrics(df: pd.DataFrame) -> dict[str, dict[str, str | None]]:
    """Detect metric columns (mean/std) from the aggregated CSV."""
    metrics: dict[str, dict[str, str | None]] = {}
    for col in df.columns:
        if not col.endswith("_mean"):
            continue
        base = col.removesuffix("_mean")
        std_col = f"{base}_std" if f"{base}_std" in df.columns else None
        metrics[base] = {
            "mean": col,
            "std": std_col,
            "count": "count" if "count" in df.columns else None,
        }
    return metrics


def add_window_labels(df: pd.DataFrame, window_size: int) -> pd.DataFrame:
    """Annotate rows with window boundaries/labels based on iteration."""
    if window_size <= 0:
        raise ValueError("window_size must be positive")

    work = df.copy()
    work["window_start"] = ((work["iteration"] - 1) // window_size) * window_size + 1
    work["window_end"] = work["window_start"] + window_size - 1
    work["window_label"] = work.apply(
        lambda row: f"{int(row.window_start)}-{int(row.window_end)}", axis=1
    )
    work["window_center"] = work["window_start"] + (window_size - 1) / 2
    return work


def plot_metric(
    df: pd.DataFrame,
    metric: str,
    mean_col: str,
    window_size: int,
    output_dir: Path,
) -> Path:
    """Plot a single metric and return the saved path."""
    work = add_window_labels(
        df[["iteration", mean_col]].rename(columns={mean_col: "metric"}), window_size
    )
    order = (
        work[["window_label", "window_start"]]
        .drop_duplicates()
        .sort_values("window_start")["window_label"]
        .tolist()
    )
    mean_line = (
        work.groupby("window_label")["metric"].mean().reindex(order).reset_index()
    )

    fig, ax = plt.subplots(figsize=(10, 4))
    sns.boxplot(
        data=work,
        x="window_label",
        y="metric",
        order=order,
        ax=ax,
        color="lightgray",
    )
    ax.plot(
        range(len(order)), mean_line["metric"], marker="o", color="C0", label="Mean"
    )
    ax.set_xlabel("Mutation iterations")
    ax.set_ylabel("BERTScore F1")
    ax.grid(True, linestyle="--", alpha=0.3)
    ax.set_xticks(range(len(order)))
    ax.set_xticklabels(order, rotation=30, ha="right")
    ax.legend()
    fig.tight_layout()

    output_dir.mkdir(parents=True, exist_ok=True)
    out_path = output_dir / f"{metric}.png"
    fig.savefig(out_path, dpi=300, bbox_inches="tight")
    plt.close(fig)
    return out_path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Create plots of semantic metrics versus mutation iteration. "
            "Input should be the CSV generated by plots/iteration_metrics.py."
        )
    )
    parser.add_argument("input_csv", help="Aggregated metrics CSV path.")
    parser.add_argument(
        "--metrics",
        nargs="*",
        default=None,
        help="Specific metrics to plot (base names without _mean); defaults to all detected.",
    )
    parser.add_argument(
        "--output-dir",
        default="plots/figures",
        help="Directory to save plots.",
    )
    parser.add_argument(
        "-w",
        "--window-size",
        type=int,
        default=20,
        help="Window size (in iterations) for smoothing (default: 20).",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    df = pd.read_csv(args.input_csv)
    if df.empty:
        raise SystemExit("Aggregated metrics CSV is empty; nothing to plot.")

    metrics = detect_metrics(df)
    if not metrics:
        raise SystemExit("No metric columns found (expected *_mean).")

    selected = metrics
    if args.metrics:
        selected = {m: metrics[m] for m in args.metrics if m in metrics}
        missing = [m for m in args.metrics if m not in metrics]
        if missing:
            print(f"Skipping unknown metrics: {', '.join(missing)}")
        if not selected:
            raise SystemExit("None of the requested metrics were found in the CSV.")

    output_dir = Path(args.output_dir)
    saved_paths: list[Path] = []
    for metric, cols in selected.items():
        saved_paths.append(
            plot_metric(
                df,
                metric=metric,
                mean_col=cols["mean"],  # type: ignore
                window_size=args.window_size,
                output_dir=output_dir,
            )
        )

    print("Saved plots:")
    for path in saved_paths:
        print(f"- {path}")


if __name__ == "__main__":
    main()
