import logging

from returns.result import Success, Failure, Result, ResultE

from .mutator import Mutator
from .seed_scheduler import Seed, SeedScheduler
from ..stance_dataset import StanceDataEntry
from ..cls import StanceAnalyzer


FuzzOutput = tuple[str, str, float]


def _construct_temp_seeds(orig_seed: Seed, rephrased_texts: list[str]) -> list[Seed]:
    """
    Construct temporary seeds from rephrased texts based on the original seed.

    The temporary seeds retain the target and stance from the original seed,
    and carry the same confidence score.
    i.e., the only change is the "text" field.

    The temporary seeds are used for evaluating the analyzer's behavior (behavior monitoring),
    then the the seed's confidence and stance will be updated based on the analyzer's output.
    """
    orig_confidence, orig_entry = orig_seed
    return [
        (
            orig_confidence,
            {
                "text": text,
                "target": orig_entry["target"],
                "stance": orig_entry["stance"],
            },
        )
        for text in rephrased_texts
    ]


class Fuzzer:
    """Content Fuzzer"""

    def __init__(
        self,
        analyzer: StanceAnalyzer,
        mutator: Mutator,
        scheduler: SeedScheduler,
    ):
        self.analyzer = analyzer
        self.mutator = mutator
        self.scheduler = scheduler

    def fuzz(self, seed: Seed) -> ResultE[list[Seed]]:
        """Returns a new input generated by fuzzing a seed in the population"""
        return self.mutator.mutate(seed[1]).map(
            lambda xs: _construct_temp_seeds(seed, xs)
        )

    def check_analyzer_behavior(self, temp_seeds: list[Seed]) -> ResultE[FuzzOutput]:
        """
        Behavior Monitoring:
            run fuzzed inputs through the analyzer,
            monitor for changes in behavior (confidence and stance).
        """
        # execute analysis
        num_added = 0
        total_generated = len(temp_seeds)
        for orig_conf, entry in temp_seeds:
            orig_stance = entry["stance"]
            match self.analyzer.analyze(entry["text"], entry["target"]):
                case Success((stance, conf)):
                    if not conf:
                        continue

                    # successful mutation if the stance is changed
                    if stance != orig_stance:
                        # update temperature energy with current success ratio
                        if total_generated:
                            self.mutator.update_energy(num_added / total_generated)
                        return Success((entry["text"], stance, conf))

                    new_entry = entry.copy()  # to avoid causing confusion
                    new_entry["stance"] = stance

                    # otherwise, add to population if confidence is improved
                    if conf and conf < orig_conf:
                        self.scheduler.add((conf, new_entry))
                        num_added += 1
                case Failure(e):
                    logging.error(f"Analysis failed: {e}")
                    continue

        # after evaluating all, update temperature energy with fraction added
        if total_generated:
            self.mutator.update_energy(num_added / total_generated)
        return Failure(Exception("No successful mutation found"))

    def run(self) -> ResultE[FuzzOutput]:
        """run one iteration of fuzzing"""
        return self.scheduler.pick().bind(self.fuzz).bind(self.check_analyzer_behavior)

    def runs(
        self, original_post: StanceDataEntry, n_iters: int = 10
    ) -> Result[FuzzOutput, list[str]]:
        """run multiple iterations of fuzzing, return the first successful seed"""
        # the initial seed is the original post with max confidence
        self.scheduler.add((1.0, original_post))
        errs: list[str] = []
        for i in range(n_iters):
            match self.run():
                case Success(seed):
                    return Success(seed)

                case Failure(e):
                    errs.append(f"{i}: {str(e)}")
        return Failure(errs)
