import logging

from returns.result import Success, Failure, Result, ResultE

from .mutator import Mutator
from .seed_scheduler import Seed, SeedScheduler
from ..stance_dataset import StanceDataEntry
from ..cls import StanceAnalyzer
from ..utils import MAX_MUTATE_RETRY


FuzzOutput = tuple[str, str, float]


class Fuzzer:
    """Content Fuzzer"""

    def __init__(
        self,
        analyzer: StanceAnalyzer,
        mutator: Mutator,
        scheduler: SeedScheduler,
    ):
        self.analyzer = analyzer
        self.mutator = mutator
        self.scheduler = scheduler

    def fuzz(
        self, seed: Seed, recur_cnt: int = 0
    ) -> ResultE[tuple[list[StanceDataEntry], Seed]]:
        """Returns a new input generated by fuzzing a seed in the population"""
        seed_stance = seed[1]

        match self.mutator.mutate(seed_stance):
            case Success(rephrased):
                # mutated seed keeps the same target and stance
                mutated_seeds: list[StanceDataEntry] = [
                    {
                        "text": text,
                        "target": seed_stance["target"],
                        "stance": seed_stance["stance"],
                    }
                    for text in rephrased
                ]
                return Success((mutated_seeds, seed))
            case Failure(e):  # request failed
                # re-try to avoid empty candidate when request failed
                if recur_cnt <= MAX_MUTATE_RETRY:
                    return self.fuzz(seed=seed, recur_cnt=recur_cnt + 1)

                # max re-try reached, fail this iteration
                return Failure(e)

        return Failure(Exception("Unreachable code in _fuzz_mutate_succ"))

    def _run(
        self, fuzz_result: tuple[list[StanceDataEntry], Seed]
    ) -> ResultE[FuzzOutput]:
        rephrased_posts, seed = fuzz_result
        original_stance = seed[1]["stance"]  # seed original stance
        original_confidence = seed[0]  # seed original confidence

        # execute analysis
        num_added = 0
        total_generated = len(rephrased_posts)
        for p in rephrased_posts:
            match self.analyzer.analyze(p["text"], p["target"]):
                case Success((stance, confidence)):
                    if not confidence:
                        continue

                    # successful mutation if the stance is changed
                    if stance != original_stance:
                        # update temperature energy with current success ratio
                        if total_generated:
                            self.mutator.update_energy(num_added / total_generated)
                        return Success((p["text"], stance, confidence))

                    p["stance"] = stance

                    # otherwise, add to population if confidence is improved
                    if confidence and confidence < original_confidence:
                        self.scheduler.add((confidence, p))
                        num_added += 1
                case Failure(e):
                    logging.error(f"Analysis failed: {e}")
                    continue

        # after evaluating all, update temperature energy with fraction added
        if total_generated:
            self.mutator.update_energy(num_added / total_generated)
        return Failure(Exception("No successful mutation found"))

    def run(self) -> ResultE[FuzzOutput]:
        """run one iteration of fuzzing"""
        return self.scheduler.pick().bind(self.fuzz).bind(self._run)

    def runs(
        self, original_post: StanceDataEntry, n_iters: int = 10
    ) -> Result[FuzzOutput, list[Exception]]:
        """run multiple iterations of fuzzing, return the first successful seed"""
        # the initial seed is the original post with max confidence
        self.scheduler.add((1.0, original_post))
        errs: list[Exception] = []
        for _ in range(n_iters):
            match self.run():
                case Success(seed):
                    return Success(seed)

                case Failure(e):
                    errs.append(e)
        return Failure(errs)
