import random
import logging
from enum import StrEnum

from returns.result import Success, Failure, Result
from ..cls import StanceAnalyzer
from .mutator import Mutator
from ..stance_dataset import StanceDataEntry
from ..utils import MAX_MUTATE_RETRY

# stance, confidence
Seed = tuple[StanceDataEntry, float]

FuzzOutput = tuple[str, str, float]


class FuzzerErr(StrEnum):
    """Error types during fuzzing"""

    NO_VALID_NEW_SEED = "No valid new seed is returned by the Mutator"
    FAILED_TO_MUTATE = "Failed to create a error triggering seed"


class Fuzzer:
    """Content Fuzzer"""

    def __init__(self, analyzer: StanceAnalyzer, mutator: Mutator):

        self.analyzer = analyzer
        self.mutator = mutator
        self.population: list[Seed] = []
        self.seed_index = 0

    def _reset(self):
        self.population = []
        self.seed_index = 0

    def fuzz(
        self, recur_cnt: int = 0
    ) -> Result[tuple[list[StanceDataEntry], Seed], FuzzerErr]:
        """Returns an input generated by fuzzing a seed in the population"""
        seed = random.choice(self.population)
        seed_stance = seed[0]
        rephrased = self.mutator.mutate(seed_stance).value_or([])

        # request failed
        if len(rephrased) == 0:
            # re-try to avoid empty candidate when request failed
            if recur_cnt <= MAX_MUTATE_RETRY:
                return self.fuzz(recur_cnt=recur_cnt + 1)

            # max re-try reached, return the same seed
            return Failure(FuzzerErr.NO_VALID_NEW_SEED)

        # mutated seed keeps the same target and stance
        mutated_seeds: list[StanceDataEntry] = [
            {
                "text": text,
                "target": seed_stance["target"],
                "stance": seed_stance["stance"],
            }
            for text in rephrased
        ]
        return Success((mutated_seeds, seed))

    def _run(
        self, fuzz_result: tuple[list[StanceDataEntry], Seed]
    ) -> Result[FuzzOutput, FuzzerErr]:
        rephrased_posts, seed = fuzz_result
        original_stance = seed[0]["stance"]  # seed original stance
        original_confidence = seed[1]  # seed original confidence

        # execute analysis
        num_added = 0
        total_generated = len(rephrased_posts)
        for p in rephrased_posts:
            match self.analyzer.analyze(p["text"], p["target"]):
                case Success((stance, confidence)):
                    if not confidence:
                        continue

                    # successful mutation if the stance is changed
                    if stance != original_stance:
                        # update temperature energy with current success ratio
                        if total_generated:
                            self.mutator.update_energy(num_added / total_generated)
                        return Success((p["text"], stance, confidence))

                    p["stance"] = stance

                    # otherwise, add to population if confidence is improved
                    if confidence and confidence < original_confidence:
                        self.population.append((p, confidence))
                        num_added += 1
                case Failure(e):
                    logging.error(f"Analysis failed: {e}")
                    continue

        # after evaluating all, update temperature energy with fraction added
        if total_generated:
            self.mutator.update_energy(num_added / total_generated)
        return Failure(FuzzerErr.FAILED_TO_MUTATE)

    def run(self) -> Result[FuzzOutput, FuzzerErr]:
        """run one iteration of fuzzing"""

        return self.fuzz(recur_cnt=0).bind(self._run)

    def runs(
        self, original_post: StanceDataEntry, n_iters: int = 10
    ) -> Result[FuzzOutput, None]:
        """run multiple iterations of fuzzing, return the first successful seed"""
        self.population.append((original_post, 1.0))
        for _ in range(n_iters):
            match self.run():
                case Success(seed):
                    return Success(seed)

                case _:
                    continue
        return Failure(None)
